### ISSUE TITLE
Crash Report -842562241

### ISSUE THREAD

**Issue by aatxxe** [wowsims/sod#850] opened 2024-07-03 19:35 UTC
Link:
https://wowsims.github.io/sod/warlock/#eJzj4uFgEmCUYDRgtGDMYHRi5wDSPxgZhRikmjm52AJyEitTiwSYJYwUOLR6GLk4BF7v4tU42CvFxSLwsImXi13g3B5eibmWXMwCz6O4uAU6gLxLbBrbZ0gCOXff8Uh0smucA6rmEGjZzaux9qIEkHXjPK/G3iaQWPseXo1rYKWdQH397Bp7gBwWgYZDvEDyym4Qefs8iNw7G0TOuwQiNwNJZoEn0UbiAsweTBGMFXwdjCwTGJkWMDJdYmS4wchl1cbC9YCJYRTQFAgtYBxoJxACr5gYnDgFmBwYAxgnMDJ6SegaGBsZGJjomhqYGhgZmBoCCSBpahjAHMGdxJD1hUmCmUuMi0OKjYuFA5gslbi4OLjYdI30jEyLhVikmKwYhIylDLk0hNS4BLX4OdiEmLwYpNi5WLmYDU2LwUIsQkxJUCFzU1UpICXQnEmCJjOopm9JQvJSslxCSgJcfJsYuYWYBFi5WDlORmswgdSBGWAFUO1wE/VMpYAu5tg2mVGDFZsCY6iCph6QAi4piFc/TWYU0pRSx3CfQbGTENC2ydEabAKMEDGD3GK4NmBmFjKTMuGCaUXyh5GBKpeQlgBQiHkXC9w4VbDjV0QjWQ0M5YITjBXTGDuhicnS4QYT4yxGhkVMbEIsHIwajErXmDkhUnkOgmC6Ic1BctZMEDhpbwmRumCvmAYG1+yNljFznF7NKyQTXJqXnZqnEJKaW5CTquBSlJien5edmafglF9cLGGiwKw1yIqID40OVDHnxRqKzBFQMHOkijuAwBBMFix3sMzM/9B6MuSqPcxohwhGAOBbmsM=

RNG Seed: 3177390963

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xd4a00, 0x102c810})
	/opt/hostedtoolcache/go/1.21.11/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/warlock.(*WarlockPet).GetPet(...)
	/home/runner/work/sod/sod/sim/warlock/pet.go:476
github.com/wowsims/sod/sim/warlock.(*Warlock).newValueWarlockCurrentPetManaPercent(0x26de000, 0x2760a50, 0x2581f50)
	/home/runner/work/sod/sod/sim/warlock/apl_values.go:195 +0x5
github.com/wowsims/sod/sim/warlock.(*Warlock).NewAPLValue(0x26de000, 0x2760a50, 0x2c32280)
	...

**Comment by kayla-glick** [comment] 2024-07-04 17:56
Pushing up a fix for this. It was caused by not having a pet

**Closed by kayla-glick** 2024-07-04 17:56 UTC
Labels: bug, Warlock
