### ISSUE TITLE
Melee hunter STR stat weigh set to 0 which is obviously simming incorrectly

### ISSUE THREAD

**Issue by Strvfeous** [wowsims/sod#267] opened 2024-02-23 15:36 UTC
**Describe the bug**
Stat weight to STR is 0

![image](https://github.com/wowsims/sod/assets/161054987/8886eb0f-9588-44db-bb8d-f545492caa82)

**Expected behavior**
That STR would hold weight

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.
https://i.imgur.com/J3PvPrS.png

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rosenrusinov** [comment] 2024-02-23 18:04
Hey, you can press the button next to DPS EP to apply the weights to your current thus making the other sim pages use them.

I will update the defaults to also not use a 0 value

**Comment by rosenrusinov** [comment] 2024-02-24 10:12
Duplicate of #276

**Closed** 2024-02-24 10:28 UTC
