### ISSUE TITLE
Crash Report 1926711792

### ISSUE THREAD

**Issue by SeriesB** [wowsims/sod#1163] opened 2024-11-17 14:56 UTC
Link:
https://wowsims.github.io/sod/retribution_paladin/#eJztVE1IVFEUfue+p3Pn2jyed8Z4Xo2mieIyMPHmDS9Sg3m5CImIWbRwWYFRISQJUTvLitHEKTeZi0ZzkYiDQtuGQgi0RfhTMRH0T0QrC0QXQp03M4n7DFt0Fvd957vf/c7hcc9lOymx4AC45AScgRkyQQYJdJFUmsAtAsMEmsMU0oSYMEZgioALKdIKU3AYxQAtnoIrIudnlan2k5fbLhiqeTCsRSeAVRm9/br5tEkuDgqmGcMZnfmMNFK5EO4tZnWzr0n+yNZjMpLRzU+6nFyrw2QUkze6LOCpKuMm6t/pMr9kMmrcz+hyvsuje0rOy0hXGX2YjPhk7opAzeOVgMx31yF6kdXlwLU6LJ1dCeC63O81sIB10yEEX2/o5sMm5D/f0e0dVDV80vsN0EIu+YZBHQN4ArAASgG0xrcae0+U//FXg6/CVrewVfGNKM01BjFJ8QJCCgYBvHHsgCO1jmU5VjzmWImYY9sJK+HEbctKxJ0UtGqnlHPdxFSZwdRxUCJ+5mMVMXuf08mCjIpKvN1dtwMRJJkai3dyTZBGhQthsmC0mqpc7dUUQRnqLDyDDrxGBJl/CJChk/dAlL98m2Cejk6PglQ54uLOh/FabguL7eG78ZDmUV9e17Pt0RAF7p+GMiGwOgNHYBv0eUoSHhTVrOIZIRSKppN5z/R3iUdYomK9BE74Ol7bgOc24I/fzY4ZWCUwW55R6s6XUYNbIDAEygKgPc44hEGCBZFp1V8SHHOrSyDk1g7d9WI22VBi5pK7ThfjVdIeUGnhaoDTo20X29rD+y0zGYboP/YkyB53U3z25v7IxxA/N6cPjHhx7XjgNpw9v3R99vjL5KHyjtsKvwC/JKYG

RNG Seed: 2836298689

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:56 +0x10
panic({0xf54c0, 0x13e41c0})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/paladin.glob..func29.1(0x2bfc9c0, 0x29b5b80)
	/home/runner/work/sod/sod/sim/paladin/item_sets_pve.go:474 +0x6
github.com/wowsims/sod/sim/core.(*Aura).init(...)
	/home/runner/work/sod/sod/sim/core/aura.go:124
github.com/wowsims/sod/sim/core.(*Aura).reset(0x2bfc9c0, 0x29b5b80)
	/home/runner...

**Comment by kayla-glick** [comment] 2024-11-17 17:03
Duplicate of https://github.com/wowsims/sod/issues/1162

**Closed by kayla-glick** 2024-11-17 17:03 UTC
