### ISSUE TITLE
Crash Report -914474084

### ISSUE THREAD

**Issue by MediaWizArt** [wowsims/sod#99] opened 2024-02-07 01:23 UTC
It happened when I swapped Hand rune from Water Shield to Molten Blast

Link:
https://wowsims.github.io/sod/enhancement_shaman/#eJzjEuFgUmAyYHRg8mBMYCxg/MHIOIGJ0YlbglGBMYJxAyNXBqMQg9QEVi62gJzEytQiATYJDQV2rX5GLhaBfxN4geSDJhC5A0iyC+xu4pX4zsjFLXAIyHjEprHhuwRQ9CiQc4MNKHocyLjPp/H7lyQXh8DZJl6NTUB5DoGrQNZlIItb4DZQwUU2jab/kiAjZ4AsWQI2fvkcEPnzMw/QuIXNvBIfGYGM1U1gBotAz2ReI1EBZg0mC2YPoB8qeBoYeToYmScwMlrNZeZ6wcQwCugChAxI1fGKicGJ1YGxg5HRS1DX1MDA1MjAyNDA1MDQ2NDUMIAlgiOJIYtJgrHgBGMDI+MsRoZJTGxSLBxMEsxKp5g5IUb4OQhCGCIOkrNmgsBJe0uIyAV7xTQwuGZvNIuZ41oTrxCHT2pZao6CiYGElgKH1iBLGh8aHahiDtcCiswRkPpPHXcgAUMw6dDvYJmZ/6H1ZMhVe0eojEMEIwBm12De

RNG Seed: 2273058019

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 422 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xb2240, 0xc61d00})
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/shaman.(*Shaman).newFlameShockSpellConfig.func5(0x283ea20, 0x28e8800, 0x2258680)
	/home/runner/work/sod/sod/sim/shaman/flame_shock.go:109 +0x18
github.com/wowsims/sod/sim/core.(*Dot).TickOnce(0x2258680, 0x283ea20)
	/home/runner/work/sod/sod/sim/core/dot.go:205 +0xa
github.com/wowsims/sod/sim/core.newDot.func1.(*Dot).basePeriodicOptions.func1(0x283ea20)
	/home/runner/work/sod/sod/sim/core/dot.go:241 +0x7
github.com/wowsims/sod/sim/core.NewPeriodicAction.func1(0x283ea20)
	/home/runner/work/sod/sod/sim/core/periodic_action.go:69 +0x6
github.com/wowsims/sod/sim/core.(*Simulation).Step(0x283ea20)...

**Comment by kayla-glick** [comment] 2024-02-08 07:21
Caused by an issue where the Flame Shock code was not checking for Molten blast rune first. Should be fixed now 👍

**Closed by kayla-glick** 2024-02-08 07:21 UTC
