### ISSUE TITLE
Flurry axe procs dont work

### ISSUE THREAD

**Issue by aloudnoise** [wowsims/sod#477] opened 2024-03-28 11:56 UTC
**Describe the bug**
Flurry axe procs dont work. Also they can proc from themselves, also WF procs can proc them, they dont have ICD. I guess stormstrike and lavalash also can proc them.

**To Reproduce**
1. Add flurry axe as weapons
2. Simulate
3. Go to log
4. See no procs

**Expected behavior**
As described flurry axe has 20% chance to proc extra attack, that have no ICD and can proc itself again, also it can proc WF weapon, and WF weapon can proc flurry axe extra attack. Same applies to stormstrike and lavalash, and other classes melee abilities, Also procs of it should have a chance to apply stack of maelstrom, but its not confirmed information.

**Sim Links and Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 123.0.6312.86

**Comment by rosenrusinov** [comment] 2024-03-28 14:38
Duplicate of #471

**Closed by rosenrusinov** 2024-03-28 14:38 UTC
