### ISSUE TITLE
Crash Report 830122584

### ISSUE THREAD

**Issue by drewdatrip** [wowsims/sod#1128] opened 2024-10-19 17:50 UTC
Link:
http://localhost:3333/sod/protection_paladin/#eJztk89rE1EQx/c7G7ubLbu8BpHNViV6kGfBskmINI2wzx6kiIccPPQkKkSrFA0eRG9BK6Q2aAgIbS8t9GDQtuRPKIKQHIy1Yg0epN4keAhCtYeCfZvk4tn64+D38JjPzPBm3mPGcHRi5GIIgqq0RDm6kScUCQuEkcM68kQ2yoQKQSBNFZwZRxUY9ePDxBBSnLpm9KQnLt3N3GKqfSoSGCjD6GWlR5b9IsVfzThGgD0sWIbGlpumPZ2Ssflt0y6k+PpXR8Ki9C5ofGsnLOG5hI8WX2vZEioSFjX+WoLOlpomr+/0S/eKdH/q5VvtnCeyzGONv30WljnvCxYvTfZLa15alcmDhspmr8r6L7+bsv7Kfcv+YkksTftn/ZsZO66DBbn/eozSHS2HQ3kYRdAqsA6lgcAm8BloAcMbAWOTlP/6rQq18Ldb+NNqkjJygNEQyvCnEGnMABcxjizODro/6YSbiLsxNx5PuG40kYhKjsVdnzpK01jwsnJdbmy2ihww1f3M/WKbUOsOry7edK2kaBDmQJGeDzAcXVeZ38C+o6tqsJNwQfR1jEERnpv1VfOSHc+ad+RKWxterKjqjXtmSD+XuZ2ZiJx0bW/gH9sUPiX25J5jy790D3N+7E0fUtH2mX0qktduth7Uzr/zTncjYgy775KHNg==

RNG Seed: 4086645189

MaxStacks required to set Aura stacks: Holy ShieldPlayer (#1)3
Stack Trace:
goroutine 158 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:124 +0x98
panic({0x185e960?, 0xc0000961e0?})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x21f
github.com/wowsims/sod/sim/core.(*Aura).SetStacks(0xc000aeb800?, 0xc000aeb8e8?, 0xfcf018?)
	/home/runner/work/sod/sod/sim/core/aura.go:199 +0x25f
github.com/wowsims/sod/sim/paladin.glob..func24.1.1(0xc000296340?, 0x1d?)
	/home/runner/work/sod/sod/sim/paladin/item_sets_pve.go:366 +0x47
github.com/wowsims/sod/sim/core.(*Aura).Activate(0xc000855040, 0xc000aa8000)
	/home/runner/work/sod/sod/sim/core/aura.go:650 +0xab1
github.com...

**Comment by kayla-glick** [comment] 2024-11-14 00:18
Caused by a variable naming issue inside of the T2 tank set code. Should be fixed now

**Closed by kayla-glick** 2024-11-14 00:18 UTC
