### ISSUE TITLE
Crash Report 1507052377

### ISSUE THREAD

**Issue by Masstachief** [wowsims/sod#1130] opened 2024-10-21 04:50 UTC
Link:
https://wowsims.github.io/sod/hunter/#eJztVE9IFGEUnzezf759tuP4ubqz3xrYkjUOrM3uOqBG7OZJJEKqg8eSjAxjIyEquoRFZqghVGpQEgRlGVGdpBDMg3aILJIORUK3Llkd8qL2zbd/UKJT9ufQG5h57/3e+733vY83WEhkTbagBlKwFy7KUO/XYQ7gPuw/CFMAVGLPCtDT1L7vROtRDXSjXDZvARZoDy+p+qutxuhoCF3aQJ+KXm2oR9XvBTg2dkHVZzzGzGfGjevc+0E1BpZ0blzhxjvVWLob4sYjTvFeNQYXw0i0wR7VGF52Yq72COY3IuZaj4j5JGJufvMbvWcc7Xm3ajzpDPPSC70qf3efcxq4wevOBlDiaveEXx9wx4u1AsNdozQox71doAwDvASpbtaFc7L0X36r0Hn42y38afkoS/U+viN8lboAGsNRy7Zti4sdTSTiFn+qY/GElbDsWJPSTFqkQ5MuXcFSxH7wohsVBDtC0IOuaMzqwGIkjOtkcKYsIuCo3cGDfYwb5GubQSI+5Go0VsX9Jdngt8Owwk1dTK6T6BYWRWpqBKi8S2KiQsyyKuLBbJJYNcbTyFi6XDEI9bNVps0SWEk3oz9SgL4H4KQ4G1xqBohCfROQ5WDiCIkcJU2ybZigMQyaJU7cWD6Of1GOdwgCzw8EsTxBiAXRT/M1O5+WCejLYpjy/sQcxtOGiyIjeSCnO/lxZuEmuhE1U+UNyC1SprJdITweKjdmPdUdImd8NETXszAWmYUOyuPF3BNWRe4i8vRjyzo9xU5imh7GkBkkbuobgWwP2Qk717IK4jkrIGbqHMIRyB3jZ2nOYPKQOPTjtMHnybzOvLTLu49MwfnsslWlFmQYAmkCSmgxUTS3Lkekygw2n2yQIxOKL2PtTBVllEAqNDToyHSyNuN5kdxwQMhsMt6vkNt3/JTsaD3W2l5ebelmudf8x/6e86dTa8KDw7/EM7muaPua9MElJt6pvlRtW3r+7PSe18kcdaoZvgNWV8aO

RNG Seed: 2320118884

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/sod/sod/sim/wasm/main.go:49 +0x10
panic({0xf2b80, 0x1399800})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/hunter.(*Hunter).applyEfficiency.func1(0x2755900)
	/home/runner/work/sod/sod/sim/hunter/talents.go:203 +0x9
github.com/wowsims/sod/sim/core.(*Unit).RegisterSpell(0x271e000, {{0x0, 0x0, 0x0, 0x0}, 0xb,...

**Comment by kayla-glick** [comment] 2024-11-14 00:21
Caused by applying to a spell with no cost. Should be fixed now

**Closed by kayla-glick** 2024-11-14 00:21 UTC
