### ISSUE TITLE
Crash Report 730092198

### ISSUE THREAD

**Issue by marcolow** [wowsims/sod#1124] opened 2024-10-15 13:25 UTC
I am unable to change my talents for my sim - it crashes the sim and logs me out of it.

Link:
https://wowsims.github.io/sod/protection_paladin/#eJztU89rE1EQ3m+ydl+f7PIMottVJHqQR0HZZo00VdhnD1LEQw4eehIVIlWKBg+it1oqpFJqUA+1l1Y8WKzR9B+QgpfkYK0FS/AgBS8SPAShaZGCvk3yH1h/HPwOw3wzHzPzHjPcYyTIRy8UlekFjdC1PKFAmCX0H2DIE7mYI5QIChkq4fQQysBAlO8jgbjhLVi8IzN88Xb2hoi5JxNm91NwJl7VbPl2yuOmGN20uSWKNdudTfOdonrPcSdOyJVvniYPJx33syPXt7o0mdeST45crruaPNKZGUu+04SJ+5OOXNrap72Xuux6U7Cg1U8sWbzj6fDrDVs+GIsEMxOOLI3t133fNGxtl75H3ecbtvvV0fT5RjPYsJOSQXTK6OEYoBzdsvLgBdAisAKjCnMN+ALUgb5Vk6+R8R+/FfE6/vYIfxo1Mvr3COrFHKIlRAZTwAUMIYcze4/4qcBP+kGQ8v2e1DFNk4EfpDI0aF4yruqjzJUxAoy3f2232iRU2lvK1Pu2l1ZVwjQo0fER3GMsJqJOOw4txjpbgvNqV8s5qrqmH0eohOlWZDk8eLmJ1TBZiLHqqB1nZ7M3s8OJ474bdv9jJyHH1bbUOVz8pTrC+7E9c2j0NG3umUpfuV6/Wzn3ITzVzqhB/AS5EoJR

RNG Seed: 4158218246

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:124 +0x10
panic({0xf2a00, 0x1397800})
	/opt/hostedtoolcache/go/1.21.13/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/paladin.glob..func24.1(0x26b91e0, 0x2c3f320)
	/home/runner/work/sod/sod/sim/paladin/item_sets_pve.go:365 +0xc
github.com/wowsims/sod/sim/core.(*Aura).init(...)
	/home/runner/work/sod/sod/sim/core/aura.go:124
github.com/wowsims/sod/sim/core.(*Aura).reset(0x26b91e0, 0x2c3f320)
	/home/runner/work/sod/sod/sim/core/aura.go:129 +0xa
github.com/wowsims/sod/sim/core.(*auraTracker).reset(0x27026a8, 0x2c3f320)
	/home/runner/work/sod/sod/sim...

**Comment by kayla-glick** [comment] 2024-11-14 00:16
Duplicate of https://github.com/wowsims/sod/issues/1123 and now fixed

**Closed by kayla-glick** 2024-11-14 00:16 UTC
