### ISSUE TITLE
Feral SoD Batch Sim Error

### ISSUE THREAD

**Issue by Stephenchisnall** [wowsims/sod#705] opened 2024-04-19 13:16 UTC
Link:
http://localhost:3333/sod/feral_druid/#eJztVU1oHVUUnnNn8t6dkzfJ5Jg0804R0mkLw0DCvEmeeckmz6pdlIipugilSA2maClafCDqqn3aIgoSIy0xFBoi2hg38tBN0kXRha0bXfiz0IVoIqIiJUWhG+udOxN9hEiKtujCs7j3m3PvPec7P/cOtkoRQQWqYkrAHvTgHdj7KFwCIIO/b8fc2NGHn5l80rW8uAfCOmCr+9uU4306GFxbKqLlvrxSQNP95qCCy3UHpfvjBSd466qn0CsKXT9fVOjDNyFY1rqP6k7wy1KiWznrBO9q3U9q3xltbHkG1HhBj19+7Kjx2tUC5txT7zuej4b6XlgtxLmgpWI+nR8+ZeHXwvhfbqnQHPzbFLaSH4SxJ1+FMZgC2MflSEm5Pyr1lhMYR/1xv5p6o/KYHMcJ48jzqsfxNpRHcmhJ1YF+HlvQ7K3UqJu7sOAjygYojTye43SiGeDTgC8BvQAYhoG0qKshSAKJAwar/ZgrKV99ETsNgWo1UYsJA3eHO5OvZw3e3hCeFIRrpvIm59oCk9UptOKoL0YKXZnTh+SambpEx29FuwEJx+S+tM5aar984yQEasOLYCTU3F8n6G3gBcBzQGcB/bAnc+41RJc0SUcWK15/2r2FlJB9D7dRJ8p5K2WnEKSILRSeQx8AXwR8D6gB2BG2J0wmDNY0B6LdN0puV+hn5LghulUZ7DUzYfXzt3CDdAf8GCPu+yu22EmE+XlLk1YANODMB70OPAd4BuhVwGP8OFbojo3ekkjMrSOJKUKPtjWftOetddgZUmYkO706GliblqY5uPWmtVgMG7SX78ZhrqAbtmWpVdZRxBHuIh/bwoJsIXPaMticVhXcsGsg0jGfXipSkbubY1T3hrOZbuft2OG3o6OKSsJtUeqVE0W9rGbayTvSGGd1YN89B2hPmxnUZFdH6QCP4310ryYAZNbTBkcoY3fYpcK1l5rdohis6f5RediX9U8pqqUE4yRTMypT2vbMKNmcX3dzSAIfxPtpDO1Fzear8xs6Y7PsJnXIsmSjsl7qK8e19KWIMyOczXQP34VDNLhllTYxGsW1P5J2iB/CB2j/3zTTlIik4dBO3rhFS6DOldYduwSzYCxCji33kR7wL5q2fkyPH652pM9qZ7U4+1oil0eGUs0nIzsOa/l8JJ4y5Rd1h+To5FOTR3vKkTcQ/sd+xldOVG+KnfrCP7Lj8vWbw0NJSY/Vc9Whx564cvLyg5+N3JmtVMfhd0wuHiA=

RNG Seed: 1170752626

no base result for equipped gear found in bulk sim

**Comment by FelixPflaum** [comment] 2024-04-20 16:24
Can't reproduce a crash with that URL, both in the online and the 0.0.5 release version. Can you provide the crash log?

**Comment by kayla-glick** [comment] 2024-04-20 19:28
Looks like an issue with the experimental Batch Sim feature. Not sure what exactly this means though

![Image](https://github.com/wowsims/sod/assets/12898988/ae447f2c-373d-4e02-bf20-c6ad16aeba96)

**Comment by kayla-glick** [comment] 2024-07-28 17:24
I'm not entirely sure @Stephenchisnall . I would not recommend using the batch sim on SoD for now until I have time to update it to the version we have on the Cata site. The one available in SoD right now was an early prototype with a lot of issues.

**Comment by kayla-glick** [comment] 2024-07-28 17:32
Created https://github.com/wowsims/sod/issues/944 so I'm going to close this issue since we have several of the same error

**Closed by kayla-glick** 2024-07-28 17:32 UTC
Labels: bug
