### ISSUE TITLE
Crash Report 971351748

### ISSUE THREAD

**Issue by Lanzercito** [wowsims/sod#782] opened 2024-06-07 04:03 UTC
Link:
https://wowsims.github.io/sod/warrior/#eJztVF1IFFEUnnNn3Z0569h0tZy9Zm1GNC1YO7OtqS9u0kP4JCghPllg0Z+KS1BvRT/2uPQgaQhbQYlFQRCRlggVJRX9YP9FP09RFEb0EAV1ZsbZSoMeKuqh83A553znfN85w72DugJRZrIUa4ERYBkGtSEDmuAyAJfEznwM1m9ctbW1U88z7Kga6wEM6x8ymvE8bI52CQzoN4Y0DOlvBzUjW0XOpSHNuBmkotfkZEPmuSsGBZ/2gfG4wDyzRzgB1R4KmRf7BCr62F7NvNAXofSbIZf1wkcnGKfgSYH5rDtCErdIIqA/uO6cD93zYB+QVg8V7ShCiRL7hzS7WA+ZUMm2hPaAkgU2AnALpHugVu8O4FMm/bc/ajwLf3uEn9lLJtWqOqSgHjIAdSJhJ+w4WaI8nownyU3G7WTcokQ9a5JXS+tf5xkyFqEighhQ6C6WKUheuR1PYyEGRQCZoZWpGMK88viiZBqLJ0rPZyCXttIG4IwJ4NWwDyQWEYmffpT10xbR8IBg1RKPiGLUysKongSnhh6Sz80NMXMylIey8rmIlyjwfdtwl3DbznYJPl/Mw0isWAlwdTAHuivZJJsrmyUETo9NozJWJwmaCuWElXYV+lt4qSiZjFZYaX87jsJb6f2BEq6KkNOldzdMnYtW9lf/EaVle5Tb7ws+m3qnTGQt9SY6rfEE4YuxgOcjngQClZFmU7ZL0RVXegpRFX52ItdbyPMFOqsrpw6AGchNfWfw6wYn+sHfgHp5mFS8YKyZLxE2LhQL/GXu0g9MxAxF5tjLHK0x0vK+rHMB/C6f+R2phIU31dVmkvdlMhpvIplGrOMrXMIgxwF3pd0tJniEzg1BIzaTMGUAvK5vED1WQAjrlBwlZMl4TnGumINFnE+uqLTcOY43R6HjMvSCNMCmCU11H8y2ZSkdDCi7Jk/EK1OR3h7HRmuqvDd1o2buGtfu1NiHZeXKUY3PatjctqG1LdrYuqljY2t0eeeqte1tG9a1RWvb02kjGZVj/9jfeHx76rfwvDj2Szx6tGLZb5mDzHLPjiOpqnXt47tGG2/X+NSpJvgCVA7aUg==

RNG Seed: 2213592996

SetStacks newStacks cannot be negative but is -1
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0x9da40, 0x29ae120})
	/opt/hostedtoolcache/go/1.21.10/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*Aura).SetStacks(0x282c9c0, 0x2858000, 0xffffffff)
	/home/runner/work/sod/sod/sim/core/aura.go:190 +0x3d
github.com...

**Comment by kayla-glick** [comment] 2024-06-09 16:23
Duplicate of https://github.com/wowsims/sod/issues/771 caused by the weapon

**Closed by kayla-glick** 2024-06-09 16:23 UTC
Labels: bug
