### ISSUE TITLE
Crash Report -1770304495

### ISSUE THREAD

**Issue by bjsmithxyz** [wowsims/sod#121] opened 2024-02-07 14:04 UTC
Link:
https://wowsims.github.io/sod/elemental_shaman/#eJzjEuNgUmA0YLRgdGBMYMxgLGBsYOKawMToxKUAFLnByPiAkVGIQWoaOxdbQE5iZWqRAJuEhgK7VisjF4vAqQm8QPJhE4jcDibXzOHl4hY43MQr8YhN49s3CS52gd6ZjBKXWbm4BBb7Sdxg09j3XYKLQ+BME6/Gn1WSQNY1IOvHL0mgrltAXd8ZNSb9lwQatBhs3IEZIGseg9m/PvMAyUXNIHbDFxC7ZzKvkYAAtwdjBFMBYwVnAyNnByOz1VxmrhdMDKOALkDIgFQdr5gYnFgdGDsYGb34jU0NDIwNTYGkgZGhqWEASwRHEkNWJ5MEM5c4F6cUOxcrx/9ADSYlLi4OLjZdMz0D02K4xEN7DWaohCmKxF1DDRaohLGeKZLE9EANdqiEEUiHkKyUNJegFj8HixBTEgNICRezuYGqFBsXC8edBYzYpM1MIdLABCukLKXIJaYlApTmzAIZfz5Qg0UKqIaL0UgKxhfikuIAa1j1XUII6AqQPMeyOiEpKQkuXiVuLk4jmIvhThfilkI4t+AEYycjJNxMHGYxMnQx8UnxcDBJcXAwCjBKMCkwKZ1i5oTIxzkIQhgiDpKzZoLASXtLiMgFe8U0MLhmbzSLmQOY44Q4fFLLUnMUTAwktBQ4tAZZfvnQ6EAVc7gWUGSOgNR/6rgDCRiCSYd+B8vM/A+tJ0Ou2jtCZRwiGAFkFYHN

RNG Seed: 276630274

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xb25e0, 0xc68d00})
	/opt/hostedtoolcache/go/1.21.6/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/shaman.(*Shaman).applyPowerSurge.func2(0x28124e0, 0x22cc6c0)
	/home/runner/work/sod/sod/sim/shaman/runes.go:243 +0x3
github.com/wowsims/sod/sim/core.(*Aura).Activate(0x28124e0, 0x22cc6c0)
	/home/runner/work/sod/sod/sim/core/aura.go:639 +0xf6
github.com/wowsims/sod/sim/shaman.(*Shaman).newFlameShockSpellConfig.func5(0x22cc6c0, 0x23b7800, 0x280c200)
	/home/runner/work/sod/sod/sim/shaman/flame_shock.go:114 +0x2a
github.com...

**Comment by kayla-glick** [comment] 2024-02-08 07:20
Caused by using power surge with Lava Burst rune not applied. Fixed in a PR earlier 👍

**Closed by kayla-glick** 2024-02-08 07:20 UTC
Labels: Shaman
