### ISSUE TITLE
Crash Report -1559699080

### ISSUE THREAD

**Issue by DJSchaffner** [wowsims/sod#627] opened 2024-04-08 21:30 UTC
Link:
https://wowsims.github.io/sod/balance_druid/#eJzj4uVgEmAyYLRgzGCcwMToxCrB+ICRUYhB6jo7F1tATmJlapEAi4SRAqNWByMXh8DVSbwa73dJcjELrLLhYhH4cJCXi11gzRxeiXZ2oOzWLzwa51dIcnEL9M5klOhk1/i/XBIov9hP4w6QwSFwegKvxo6vEkDWxSZejdbdIJU3mngl+tk1DgGFWQQOz2AEkoubeIHkUzB5+zwv0LJFIMs2zQYJrJrNa8SUwWjVxsL1gIlhFNAUCC1gHGgnEAKvmBicGLyETQ0MjE0NDA0MjExNDY1NDXV1TQNYIjiSGLK+M0owc4lzcUqxc7FyTPbVYFXi4uLgYtM10rO0LBaSl5LlkhQCSm9iZONi4QClSa5ZjCClL300OKwYhDSk1LhkhKS4OGfBFfAqcSOpl4LSQrpS2lyKQvJcPCALjECioFTPr8XLwSbE5MUgxcrFzMVoKQWVENKX0uVSElKAmGYEsxFTPUxGSExKBNlamHeExKVEYW4+6arBLgVjFJxg7IRGn4jDLEaGRYwsUkxcDEoHmDkhonEOgjBpyVkzQeCkvSVE5IK9YhoYXLM3msDMcb2JV4jDJ7UsNUfB1EDCRGuQ5bwPjQ5UMadpBUXmCEj9p447gMAQTDrMd7DMzP/QejLkqr0jVMYhghEAfUt9hg==

RNG Seed: 2697812402

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xcaf40, 0xf04250})
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*Aura).Activate(0x0, 0x23a18c0)
	/home/runner/work/sod/sod/sim/core/aura.go:550 +0x2
github.com/wowsims/sod/sim/druid.(*Druid).applyDreamstate.func4(0x23f4680, 0x23a18c0, 0x23f6000, 0x23f61d0)
	/home/runner/work/sod/sod/sim/druid/runes.go:309 +0x14
github.com/wowsims/sod/sim/core.(*auraTracker).OnSpellHitDealt(...)
	/home/runner/work/sod/sod/sim/core/aura.go:801
github.com/wowsims/sod/sim/core.(*Spell).dealDamageInternal(0x23f6000, 0x23a18c0, 0x0,...

**Comment by DJSchaffner** [comment] 2024-04-08 21:30
More info:

https://wowsims.github.io/sod/balance_druid/#eJzj4uVgEmAyYLRgzGCcwMToxCrB+ICRUYhB6jo7F1tATmJlapEAi4SRAqNWByMXh8DVSbwa73dJcjELrLLhYhH4cJCXi11gzRxeiXZ2oOzWLzwa51dIcnEL9M5klOhk1/i/XBIov9hP4w6QwSFwegKvxo6vEkDWxSZejdbdIJU3mngl+tk1DgGFWQQOz2AEkoubeIHkUzB5+zwv0LJFIMs2zQYJrJrNa8SUwWjVxsL1gIlhFNAUCC1gHGgnEAKvmBicGLyETQ0MjE0NDA0MjExNDY1NDXV1TQNYIjiSGLK+M0owc4lzcUqxc7FyTPbVYFXi4uLgYtM10rO0LBaSl5LlkhQCSm9iZONi4QClSa5ZjCClL300OKwYhDSk1LhkhKS4OGfBFfAqcSOpl4LSQrpS2lyKQvJcPCALjECioFTPr8XLwSbE5MUgxcrFzMVoKQWVENKX0uVSElKAmGYEsxFTPUxGSExKBNlamHeExKVEYW4+6arBLgVjFJxg7IRGn4jDLEaGRYwsUkxcDEoHmDkhonEOgjBpyVkzQeCkvSVE5IK9YhoYXLM3msDMcb2JV4jDJ7UsNUfB1EDCRGuQ5bwPjQ5UMadpBUXmCEj9p447gMAQTDrMd7DMzP/QejLkqr0jVMYhghEAfUt9hg==

**Comment by DJSchaffner** [comment] 2024-04-08 21:32
Happens everytime i activate https://www.wowhead.com/classic/item=10646/goblin-sapper-charge

**Comment by kayla-glick** [comment] 2024-04-09 04:21
Looks like the issue is using the sapper and it critting is trying to apply dreamstate to the player. I'm trying to find out if dreamstate is even applied by bombs in the first place

**Comment by kayla-glick** [comment] 2024-04-11 20:54
This should be fixed now

**Closed by kayla-glick** 2024-04-11 20:54 UTC
Labels: bug, Druid
