### ISSUE TITLE
Crash Report -794627450

### ISSUE THREAD

**Issue by Dillv40** [wowsims/sod#384] opened 2024-03-12 02:04 UTC
Link:
https://wowsims.github.io/sod/hunter/#eJzj4uZgEmAyYHRgmsDE6MQqwbiB0U2IQeoZOxdbQE5iZWqRAKOEpAKTVhsjF4vAvwm8QPLKDBB7RxOIvQdI8gjsszI4yCwhqPHmvwRQ7OZCXi4ugfufeYAiM/5JcHEInJ7Aq/FjjSSQdbWJV+MGmHUbyLreIAlUvwRs0m6wqb2TQeyfn3m42AUWNvNKrLIAMg5BGCwCR2bzGjFYtbFwPWBiGAU0BUILGAfaCYTAKyYGJxYBJgkmLwMDUwMDYyMQZWpkaGRqqGuAAtC4BgYBLBEcSQxZzxglGLnEuDil2LlYOd7lazApcXIBmbqGeqbFXMIw8UwNZiU2LhYuJoNiIW4piOBlEQ1GIS4pDimgBMfqeVJCYlIiTkJQ1QLMIDVczAa5CA2n8jWY4RqAOUCIVwooxcXOsS1fgVGDRchcypRLU0idS1RLmINNiPUQExMHqxQHF1A12DF8SjxcXIsYYVZPYgRbwMVoKqQspYisiQmhCa7IouAE4yxGhkOMgkL8HIwSTEoMmpAQ/GCvdIqZE8L2cxCEMEQcJGfNBIGT9pYQkQv2imlgcM3eaBYzx7UmXiEOn9Sy1BwFI1MJaQUOrReDKzt+aHSgijkOEykyR0DqP3XcgQQMIVSlg2Vm/ofWkyFX7R2hMg4RjAClK3xa

RNG Seed: 3118943380

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xc42a0, 0xe420f0})
	/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/core.(*Aura).Activate(0x0, 0x282b8c0)
	/home/runner/work/sod/sod/sim/core/aura.go:550 +0x2
github.com/wowsims/sod/sim/common/sod/item_effects.init.0.func7.1(0x282b8c0, 0x23f8a80, 0x287e500)
	/home/runner/work/sod/sod/sim/common/sod/item_effects/phase_2.go:359 +0xb
github.com/wowsims/sod/sim/core.(*Spell).applyEffects(0x287e500, 0x282b8c0, 0x23f8a80)
	/home/runner/work/sod/sod/sim/core/spell.go:548 +0x9
github.com/wowsims/sod/sim...

**Comment by kayla-glick** [comment] 2024-03-12 05:21
Hey @Dillv40 this crash is due to your character being level 40 while using the the Mekkatorque's Arcano Shredder mainhand that requires level 40. You can fix this issue by changing your character to level 40 in the settings tab

![Image](https://github.com/wowsims/sod/assets/12898988/7167281a-0f10-4cdd-ad0d-e047ef048e3e)

Duplicate of https://github.com/wowsims/sod/issues/349

**Closed** 2024-03-12 05:52 UTC
