### ISSUE TITLE
Crash Report -228145437

### ISSUE THREAD

**Issue by Vancopland** [wowsims/sod#963] opened 2024-08-09 05:20 UTC
Link:
https://wowsims.github.io/sod/tank_warlock/#eJztVU1o1FAQ3nnJ7r6dNTW+upo+l1L3oM+FlezaLa0KG0VERLTipSiIihWVIsWC1FtRQaVV6w+lKhbxIBURpQhKQawgWA/W+oNUVKjgoRQPHoStCuokm7XFHxDtwYNDSOb7Zr7JvLxMguWcmcxiNlSDw7ZDP+uHFoAWtqudwTVgS2dzsKCbfAYODAJxW7dDM1sB5xmMAWthbCEzQQRk9xQM1TZs3lu/m+otruDJS4BR89Vbw3odVX1HJOrmnbyBYfNVl2G1LqLYufeG1bZI3Ri0CLwk9k2JevrIBUMEzobVAKmi5nMC90rVg8cWcvP5W0Pd2ufSL7q8yvlPZQSeETgWVp87yyjndt5QRw/MIu8kecfJ082BjwadXzx0G+gaM6z+UoJ3P7jkxbyRqeaaGVGwgtVCHT2FRq05dgjMdmDnQbsG+k2gtUIfwGNgFTAE4WGAEYB3EFw4oOMwC/y337DVzp8qxQhMYh//tI2ywNIZ7kRWQzfQyNVCJ8AmoHcSVpanMnbWpiOdzdh2OmVnCdnZtJ0hKp2t1er0LYGdo7qlYQy5DKHOaWoSEQxjMJW27Sac7tNvTkCCI3mpGmJjiJIQP9AGiiUoGbVUZZOIyLAk1zy2Q8RkKUYugCulgZP+VayVa3C5WIYlPRAVzAxikN/fqjQ0egA9rPOBs3GM9HjKezS3vjtGUzsh6WpH3LtTxzpRJSsxKRUaiWgxubs1jjOTMa6LSG+RcFtAlmnyWml9YomZMlbMv5yfNb4cr+A8MRdF0qQKWo8ekN4KF9g2TktO5UHBVvpU2m5yHX5pgwqN6xLmxPXdoZinC03QVRV0bkxk5QJUYs73uuuuzkyW+DqvfV/mhsQSmcNKkfkxBcuTca6Jkt5vpU5tUGHp7V56frZQwqV+1XHnzzrOFHRuTEyRhe2/cRImoP1tLiqXcU+rC7be11bZ9ren1NgPzR3uD+OwP6DTnTEGQwyGGZyBaMTjGg86FaFexkWI/jWgINGnFQKBjc60oqzszGnX7udqCsxgbvY2z57lMu0aH9pnCL6qfk99Q0WVbeWS/9g3Vx12JqXOnCt/VceUXyanD7K0d3auOjXFnVniR5w6+AqKc+O+

RNG Seed: 4240812615

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/sod/sim/core.runSim.func1()
	/home/runner/work/sod/sod/sim/core/sim.go:123 +0x10
panic({0xe6080, 0x12310d0})
	/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x2c
github.com/wowsims/sod/sim/warlock.(*Warlock).applyCataclysm.func1(0x2c82280)
	/home/runner/work/sod/sod...

**Comment by kayla-glick** [comment] 2024-08-09 16:20
Pushed a fix for this. It was caused by using Immolation Aura with the Cataclysm talent

**Closed by kayla-glick** 2024-08-09 16:20 UTC
Labels: bug, Warlock

**Comment by Vancopland** [comment] 2024-08-09 19:39
oh fantastic, thank you! aha what a funny bug
